# This file was generated by GoReleaser. DO NOT EDIT.
cask "agentico" do
  version "0.157.1"

  on_macos do
    on_intel do
      sha256 "5e774244ff2251b74b4c33dececc50205e91dbe23890654f03ebaeaa073c0f1b"
      url "https://github.com/doordash-oss/agentic-orchestrator/releases/download/v#{version}/agentic-orchestrator_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "182825d0cc3621b272924962df5276a18a5bda879a930fd322219a42b2f71633"
      url "https://github.com/doordash-oss/agentic-orchestrator/releases/download/v#{version}/agentic-orchestrator_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "e833baad58ec4769d909f95e22e2e320d4dd39c2bba087adcb42688a00776113"
      url "https://github.com/doordash-oss/agentic-orchestrator/releases/download/v#{version}/agentic-orchestrator_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "678dafa0c86d44b44c47191e624335e5132f218360b62cec658e6805341913a2"
      url "https://github.com/doordash-oss/agentic-orchestrator/releases/download/v#{version}/agentic-orchestrator_#{version}_linux_arm64.tar.gz"
    end
  end

  name "agentico"
  desc "Desktop-first parallel agentic coding orchestrator"
  homepage "https://github.com/doordash-oss/agentic-orchestrator"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "agentico"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/agentico"]
    end
  end

  # No zap stanza required

end
