# This file was generated by GoReleaser. DO NOT EDIT.
cask "agentico" do
  version "0.157.0"

  on_macos do
    on_intel do
      sha256 "8082d4c95a9e133314d35ea478245072073e358482abef96dcb1dd4a1353da95"
      url "https://github.com/doordash-oss/agentic-orchestrator/releases/download/v#{version}/agentic-orchestrator_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "5c68602e93510b96801b7ea73381d29fe56498819a1966d48140a16649514401"
      url "https://github.com/doordash-oss/agentic-orchestrator/releases/download/v#{version}/agentic-orchestrator_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "8c63ade2cfc2138e0f500531d50a12eacd7f294d2294149276884e0a18b15304"
      url "https://github.com/doordash-oss/agentic-orchestrator/releases/download/v#{version}/agentic-orchestrator_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "dd6f6b1615d5ebdceaf3a4f31fb4a90d9bd058d67d841aeec4725dc15bddf013"
      url "https://github.com/doordash-oss/agentic-orchestrator/releases/download/v#{version}/agentic-orchestrator_#{version}_linux_arm64.tar.gz"
    end
  end

  name "agentico"
  desc "Desktop-first parallel agentic coding orchestrator"
  homepage "https://github.com/doordash-oss/agentic-orchestrator"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "agentico"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/agentico"]
    end
  end

  # No zap stanza required

end
