# Generated by desktop/scripts/publish-desktop-cask.mjs — do not edit by hand.
cask "agentico-desktop" do
  version "0.149.0"
  sha256 "4ae73e1909441fadfb12b5f0de74380f92d3bc38e279418f98637045d280f12a"

  url "https://github.com/doordash-oss/agentic-orchestrator/releases/download/v#{version}/Agentico-mac-universal.dmg"
  name "Agentico"
  desc "Desktop-first parallel agentic coding orchestrator"
  homepage "https://github.com/doordash-oss/agentic-orchestrator"

  # The app updates itself in place through its verified in-app updater;
  # `brew upgrade --greedy` still refreshes it from the tap.
  auto_updates true

  app "Agentico.app"

  # The DMG is not yet Developer ID-signed or notarized; Homebrew quarantines
  # its downloads, and Gatekeeper refuses quarantined unsigned apps. Remove
  # once releases are notarized.
  postflight do
    system_command "/usr/bin/xattr",
                   args: ["-dr", "com.apple.quarantine", "#{appdir}/Agentico.app"]
  end

  zap trash: [
    "~/Library/Application Support/Agentico",
    "~/Library/Caches/com.doordash.agentico",
    "~/Library/Preferences/com.doordash.agentico.plist",
    "~/Library/Saved Application State/com.doordash.agentico.savedState",
  ]
end
