# This file was generated by GoReleaser. DO NOT EDIT.
cask "agentico" do
  version "0.154.0"

  on_macos do
    on_intel do
      sha256 "18cb8f840058ce148b8f86285a39987d9c16e6340ed3df4bbd2a9cc4e7117122"
      url "https://github.com/doordash-oss/agentic-orchestrator/releases/download/v#{version}/agentic-orchestrator_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "fd339a9811246c51d1d3221ee394f4716897d062bd65bce2f47cd621806f22e7"
      url "https://github.com/doordash-oss/agentic-orchestrator/releases/download/v#{version}/agentic-orchestrator_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "2739cbe32fc1e0f3f252a294955101f0ed645a8facf3c91eec4182ad738ead0c"
      url "https://github.com/doordash-oss/agentic-orchestrator/releases/download/v#{version}/agentic-orchestrator_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "3493b9af3ceedfff0e91ab695a3f891dedb184769bf738e17d9c525952e57cb0"
      url "https://github.com/doordash-oss/agentic-orchestrator/releases/download/v#{version}/agentic-orchestrator_#{version}_linux_arm64.tar.gz"
    end
  end

  name "agentico"
  desc "Desktop-first parallel agentic coding orchestrator"
  homepage "https://github.com/doordash-oss/agentic-orchestrator"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "agentico"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/agentico"]
    end
  end

  # No zap stanza required

end
