# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Agentico < Formula
  desc "Parallel agentic coding orchestrator TUI"
  homepage "https://github.com/doordash-oss/agentic-orchestrator"
  version "0.143.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/doordash-oss/agentic-orchestrator/releases/download/v0.143.0/agentic-orchestrator_0.143.0_darwin_amd64.tar.gz"
      sha256 "663854bdbb48c08a71a1752beb49e6895f63294a1aa60eb49e860b65ece027d7"

      define_method(:install) do
        bin.install "agentico"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/doordash-oss/agentic-orchestrator/releases/download/v0.143.0/agentic-orchestrator_0.143.0_darwin_arm64.tar.gz"
      sha256 "0431445d316b6a84e556c1220476f2a59811ad2e916ca11333c8063ae7793374"

      define_method(:install) do
        bin.install "agentico"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/doordash-oss/agentic-orchestrator/releases/download/v0.143.0/agentic-orchestrator_0.143.0_linux_amd64.tar.gz"
      sha256 "37d61fdf04f221aad571243491dfea6b6fe61db909dc85565ed6a2da389fde7b"
      define_method(:install) do
        bin.install "agentico"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/doordash-oss/agentic-orchestrator/releases/download/v0.143.0/agentic-orchestrator_0.143.0_linux_arm64.tar.gz"
      sha256 "c02e0a697c33b80bad2ea8666006feb93a010895ee3e9de4c95d4597a39c9833"
      define_method(:install) do
        bin.install "agentico"
      end
    end
  end

  test do
    system "#{bin}/agentico", "--version"
  end
end
