# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Agentico < Formula
  desc "Parallel agentic coding orchestrator TUI"
  homepage "https://github.com/doordash-oss/agentic-orchestrator"
  version "0.144.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/doordash-oss/agentic-orchestrator/releases/download/v0.144.1/agentic-orchestrator_0.144.1_darwin_amd64.tar.gz"
      sha256 "8a891413d1c58e8050a1f46f954de048c90b9902e245cf0baa09776975136554"

      define_method(:install) do
        bin.install "agentico"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/doordash-oss/agentic-orchestrator/releases/download/v0.144.1/agentic-orchestrator_0.144.1_darwin_arm64.tar.gz"
      sha256 "3b83801259c09352e74e82ed25b99c11993c6eef281b1cd94879faea349174ce"

      define_method(:install) do
        bin.install "agentico"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/doordash-oss/agentic-orchestrator/releases/download/v0.144.1/agentic-orchestrator_0.144.1_linux_amd64.tar.gz"
      sha256 "db7f369ed1a26351a64e019052575cdfbd16a24e49f8e737813f17252db30ccb"
      define_method(:install) do
        bin.install "agentico"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/doordash-oss/agentic-orchestrator/releases/download/v0.144.1/agentic-orchestrator_0.144.1_linux_arm64.tar.gz"
      sha256 "d59068d173a25eb6859e8fee41103431d5dd441127d56e2080d56c43c9df35ba"
      define_method(:install) do
        bin.install "agentico"
      end
    end
  end

  test do
    system "#{bin}/agentico", "--version"
  end
end
